theme        = "lpgn"
baseURL      = "https://leplusgrandnombre.fr"
languageCode = "fr"
title        = "Le Plus Grand Nombre"

enableRobotsTXT = true
summaryLength   = 30
buildDrafts     = false
buildFuture     = false

[params]
  description = "Solutions num√©riques pour les artisans et professionnels"

[pagination]
  pagerSize = 10

[taxonomies]
  tag      = "tags"
  category = "categories"

[sitemap]
  changefreq = "weekly"
  filename   = "sitemap.xml"
  priority   = 0.5

[outputs]
  home = ["HTML", "RSS"]
