[[main]]
  name = "Ã€ propos"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Applications"
  pageRef = "applications"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40
