[[main]]
  name = "Nos convictions"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Quelques id√©es"
  pageRef = "applications"
  weight = 20

[[main]]
  name = "Points de vue"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40
