# -- Menu Principal --

[[main]]
  name = "Ã€ propos"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Applications"
  pageRef = "apps"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40

# -- Menu Pied de Page --

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20
